### ISSUE TITLE
Keyboard does not reappear

### ISSUE THREAD

**Issue by MangoHiller** [NathanFallet/OCaml#29]
When you edit a new file and then execute it and after execution if you want to return to the file, the keyboard does not reappear, forcing you to close the file manually and then reopen it.

Device: iPhone XS MAX, IOS 14.2

https://user-images.githubusercontent.com/45636497/149910937-cec40a65-5615-4398-9244-0dbc9ce52d34.MP4

**Comment by NathanFallet** [comment]
Might be solved by #27 if we replace Sourceful by Runestone (when available, cc @simonbs)

**Comment by OlegAlexander** [comment]
Thank you for creating this app, @NathanFallet ! And thank you @MangoHiller for reporting this issue. The issue still exists in the current version on iPhone. The only thing I would add is that it's also possible to bring back the keyboard by opening and closing the settings (gear icon).  

Also, sometimes it's useful to close the keyboard to admire your code in full screen. Some apps, like Pythonista, allow you to swipe down the keyboard to close it. Tapping in the text editor brings it back. Switching between the editor and the console maintains the keyboard open/closed state. Similarly, CarbonFin Outliner, has a button to close the keyboard to show the outline in full screen. Tapping on the outline text brings it back.

These are just ideas to improve the keyboard UX. Again, thanks for creating this awesome app!

**Comment by NathanFallet** [comment]
This issue seems to be fixed with the update I just compiled. I don't know if it's a change in the compiler, in the Sourceful library or in an update of iOS, but at least it works. I'm sending the updated version to TestFlight and to the App Store.
